ARCH:
  ENTROPY_REGULARIZATION: False
  L1_REGULARIZATION: False
  HARD_ARCH_TRAINING: False
  HARD_WEIGHT_TRAINING: False
  SEARCHSPACE: GeneralizedMTLNAS
MODEL:
  SUPERNET: True
  BACKBONE: VGG16_13_Stage
  INIT: (0.9, 0.1)
  NET1_CLASSES: 40
  NET2_CLASSES: 3
TRAIN:
  EVAL_CKPT: True
  LOG_INTERVAL: 500
  LR: 0.001
  SAVE_INTERVAL: 5000
  WEIGHT_1: Seg
  WEIGHT_2: Normal